name: Build Docker

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Build
        run: docker build .
     
      
      - uses: anc95/ChatGPT-CodeReview@main
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  
            LANGUAGE: English
            OPENAI_API_ENDPOINT: https://api.openai.com/v1
            MODEL: gpt-3.5-turbo 
            PROMPT: Please check if there are any confusions or irregularities in the following code diff:
            top_p: 1 
            temperature: 1 
            max_tokens: 10000
            MAX_PATCH_LENGTH: 10000 
            
